drop table if exists task;

CREATE TABLE
    IF NOT EXISTS task (
        id bigint PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        assigned_time timestamp
        with
            time zone not null,
            collected_time timestamp
        with
            time zone,
            delivered_time timestamp
        with
            time zone,
            people_id bigint references people(id),
            machine_id int references machine(id)
    );

INSERT INTO
    task (
        assigned_time,
        collected_time,
        delivered_time,
        people_id,
        machine_id
    )
VALUES (
        '2022-10-15 09:00',
        '2022-10-17 09:00',
        '2022-10-18 09:00',
        1,
        2
    );

drop table if exists machine;

CREATE TABLE
    IF NOT EXISTS machine (
        id int PRIMARY KEY UNIQUE NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        name varchar(100) not null,
        current_load decimal not null,
        capacity decimal not null,
        status varchar(50) not null,
        location_id bigint references location(id)
    );

INSERT INTO
    machine (
        name,
        current_load,
        capacity,
        status,
        location_id
    )
VALUES (
        'Commonwealth_1',
        0.8,
        2,
        'normal',
        1
    ), ('BoonLay_1', 1.2, 2, 'faulty', 2);

ALTER TABLE machine ADD COLUMN unit_number VARCHAR;

ALTER TABLE machine RENAME COLUMN unit_number unitNumber;

CREATE TYPE status_type AS ENUM('FAULTY', 'NORMAL');